[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive"] }
which = "8.0.0"
tar = "0.4.44"
flate2 = "1.1.9"
prost-build = "0.14.3"
procfs = "0.18.0"
serde_json = "1.0.149"
lalrpop = "0.22.2"
